# Preliminary analysis of Movies Dataset

In [48]:
import os
while os.path.basename(os.getcwd()) != "ada-project-private":
    os.chdir('..')

import pandas as pd
import json

DATA_FOLDER = './MovieSummaries/'

# Load character.metadata.tsv
character_metadata_cols = ["Wikipedia movie ID", "Freebase movie ID",
                           "Movie release date", "Character name",
                           "Actor date of birth", "Actor gender", "Actor height (in meters)", "Actor ethnicity (Freebase ID)",
                           "Actor name", "Actor age at movie release",
                           "Freebase character/actor map ID", "Freebase character ID", "Freebase actor ID"]
character_metadata_df = pd.read_csv(DATA_FOLDER + 'character.metadata.tsv', sep='\t', header=None, names=character_metadata_cols)

# Load movie.metadata.tsv
movie_metadata_cols = ["Wikipedia movie ID", "Freebase movie ID", "Movie name", "Movie release date", "Movie box office revenue", "Movie runtime",
                       "Movie languages (Freebase ID:name tuples)", "Movie countries (Freebase ID:name tuples)",
                       "Movie genres (Freebase ID:name tuples)"]
movie_metadata_df = pd.read_csv(DATA_FOLDER + 'movie.metadata.tsv', sep='\t', header=None, names=movie_metadata_cols)

# Load name.clusters.txt
name_clusters_cols = ["Character name", "Freebase movie ID"]
name_clusters_df = pd.read_csv(DATA_FOLDER + 'name.clusters.txt', sep='\t', header=None, names=name_clusters_cols)

# Load plot_summaries.txt
plot_summaries_cols = ["Wikipedia movie ID", "Wikipedia plot"]
plot_summaries_df = pd.read_csv(DATA_FOLDER + 'plot_summaries.txt', sep='\t', header=None, names=plot_summaries_cols)

# Load tvtropes.clusters.txt
tvtropes_clusters_cols = ["Character types", "details"]
tvtropes_clusters_df = pd.read_csv(DATA_FOLDER + 'tvtropes.clusters.txt', sep='\t', header=None, names=tvtropes_clusters_cols)

tvtropes_clusters_df["details_dict"] = tvtropes_clusters_df["details"].apply(json.loads)
tvtropes_clusters_df["Character name"] = tvtropes_clusters_df["details_dict"].apply(lambda x: x.get('char'))
tvtropes_clusters_df["Movie name"] = tvtropes_clusters_df["details_dict"].apply(lambda x: x.get('movie'))
tvtropes_clusters_df["Freebase character/actor map ID"] = tvtropes_clusters_df["details_dict"].apply(lambda x: x.get('id'))
tvtropes_clusters_df["Actor name"] = tvtropes_clusters_df["details_dict"].apply(lambda x: x.get('actor'))

tvtropes_clusters_df.drop(columns=["details", "details_dict"], inplace=True)

In [50]:
def print_missing_stats(df):
    print("total len:", len(df))
    for col in df.columns:
        print("missing " + col + ":", sum(df[col].isna()))

In [5]:
print_missing_stats(character_metadata_df)

print("")
print("missing Freebase actor ID but not Actor name:", sum(character_metadata_df["Freebase actor ID"].isna() & character_metadata_df["Actor name"].notna()))
print("We drop all the rows that have NA in the column \"Freebase actor ID\"")
character_metadata_df = character_metadata_df.dropna(subset=["Freebase actor ID"])

print("")
print_missing_stats(character_metadata_df)

character_metadata_df[character_metadata_df["Freebase movie ID"] == "/m/03vyhn"].head()

total len: 450669
missing Wikipedia movie ID: 0
missing Freebase movie ID: 0
missing Movie release date: 9995
missing Character name: 257875
missing Actor date of birth: 106145
missing Actor gender: 45609
missing Actor height (in meters): 295845
missing Actor ethnicity (Freebase ID): 344611
missing Actor name: 1228
missing Actor age at movie release: 158113
missing Freebase character/actor map ID: 0
missing Freebase character ID: 257865
missing Freebase actor ID: 815

missing Freebase actor ID but not Actor name: 0
We drop all the rows that have NA in the column "Freebase actor ID"

total len: 449854
missing Wikipedia movie ID: 0
missing Freebase movie ID: 0
missing Movie release date: 9980
missing Character name: 257389
missing Actor date of birth: 105330
missing Actor gender: 44794
missing Actor height (in meters): 295030
missing Actor ethnicity (Freebase ID): 343796
missing Actor name: 413
missing Actor age at movie release: 157298
missing Freebase character/actor map ID: 0
missing Freebase character ID: 257379
missing Freebase actor ID: 0

,Wikipedia movie ID,Freebase movie ID,Movie release date,Character name,Actor date of birth,Actor gender,Actor height (in meters),Actor ethnicity (Freebase ID),Actor name,Actor age at movie release,Freebase character/actor map ID,Freebase character ID,Freebase actor ID
0,975900,/m/03vyhn,2001-08-24,Akooshay,1958-08-26,F,1.620,NaN,Wanda De Jesus,42.0,/m/0bgchxw,/m/0bgcj3x,/m/03wcfv7
1,975900,/m/03vyhn,2001-08-24,Lieutenant Melanie Ballard,1974-08-15,F,1.780,/m/044038p,Natasha Henstridge,27.0,/m/0jys3m,/m/0bgchn4,/m/0346l4
2,975900,/m/03vyhn,2001-08-24,Desolation Williams,1969-06-15,M,1.727,/m/0x67,Ice Cube,32.0,/m/0jys3g,/m/0bgchn_,/m/01vw26l
3,975900,/m/03vyhn,2001-08-24,Sgt Jericho Butler,1967-09-12,M,1.750,NaN,Jason Statham,33.0,/m/02vchl6,/m/0bgchnq,/m/034hyc
4,975900,/m/03vyhn,2001-08-24,Bashira Kincaid,1977-09-25,F,1.650,NaN,Clea DuVall,23.0,/m/02vbb3r,/m/0bgchp9,/m/01y9xg

In [51]:
print_missing_stats(movie_metadata_df)

movie_metadata_df.head(10)

total len: 81741
missing Wikipedia movie ID: 0
missing Freebase movie ID: 0
missing Movie name: 0
missing Movie release date: 6902
missing Movie box office revenue: 73340
missing Movie runtime: 20450
missing Movie languages (Freebase ID:name tuples): 0
missing Movie countries (Freebase ID:name tuples): 0
missing Movie genres (Freebase ID:name tuples): 0

,Wikipedia movie ID,Freebase movie ID,Movie name,Movie release date,Movie box office revenue,Movie runtime,Movie languages (Freebase ID:name tuples),Movie countries (Freebase ID:name tuples),Movie genres (Freebase ID:name tuples)
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/01jfsb"": ""Thriller"", ""/m/06n90"": ""Science..."
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey ...,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/02n4kr"": ""Mystery"", ""/m/03bxz7"": ""Biograp..."
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""D..."
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/01jfsb"": ""Thriller"", ""/m/0glj9q"": ""Erotic..."
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}","{""/m/07s9rl0"": ""Drama""}"
5,13696889,/m/03cfc81,The Gangsters,1913-05-29,NaN,35.0,"{""/m/06ppq"": ""Silent film"", ""/m/02h40lc"": ""Eng...","{""/m/09c7w0"": ""United States of America""}","{""/m/02hmvc"": ""Short Film"", ""/m/06ppq"": ""Silen..."
6,18998739,/m/04jcqvw,The Sorcerer's Apprentice,2002,NaN,86.0,"{""/m/02h40lc"": ""English Language""}","{""/m/0hzlz"": ""South Africa""}","{""/m/0hqxf"": ""Family Film"", ""/m/01hmnh"": ""Fant..."
7,10408933,/m/02qc0j7,Alexander's Ragtime Band,1938-08-16,3600000.0,106.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/04t36"": ""Musical"", ""/m/01z4y"": ""Comedy"", ..."
8,9997961,/m/06_y2j7,Contigo y aquí,1974,NaN,NaN,"{""/m/06nm1"": ""Spanish Language""}","{""/m/0jgd"": ""Argentina""}","{""/m/04t36"": ""Musical"", ""/m/07s9rl0"": ""Drama"",..."
9,2345652,/m/075f66,City of the Dead,1960,NaN,76.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/03npn"": ""Horror"", ""/m/0fdjb"": ""Supernatur..."

In [7]:
print("total len:", len(plot_summaries_df))

# plot_summaries_df.head(10)

total len: 42303

SELECT ?s ?sLabel ?freebaseID ?duration
WHERE {
  
  VALUES ?freebaseID { 
    "/m/03vyhn" 
    "/m/0crgdbh" 
  }
  
  ?s wdt:P646 ?freebaseID .
  
  OPTIONAL { ?s wdt:P2047 ?duration }
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }
  
}

In [8]:
import requests

def download_sparql_csv(query, file_path):
    url = 'https://query.wikidata.org/sparql'
    
    response = requests.get(url, params={'query': query}, headers={'Accept': 'text/csv'})
    
    if response.status_code == 200:
        with open(file_path, 'wb') as file:
            file.write(response.content)
        return True
    else:
        print(f"Error: Failed to retrieve data. Status code {response.status_code}")
        return False

In [7]:
generic_query = '''
SELECT ?s ?sLabel ?freebaseID ?duration
WHERE {
  VALUES ?freebaseID {
|
  }
  
  ?s wdt:P646 ?freebaseID .
  
  OPTIONAL { ?s wdt:P2047 ?duration }
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }
}
'''

In [8]:
# n = len(movie_metadata_df)
# step = 100

# low = 0
# c = 1
# while low < n:
#     up = min(low + step, n)

#     ids_string = "\n".join(movie_metadata_df["Freebase movie ID"][low:up].astype(str).apply(lambda x: "\"" + x + "\""))
#     query = generic_query.replace("|",ids_string)
    
#     success = download_sparql_csv(query, f"AdditionalData/duration_{c:04d}.csv")
    
#     if success:
#         low = up
#         c += 1
    
#     print(f"{up}/{n} done")

# pd.concat([pd.read_csv(f"AdditionalData/duration_{i:04d}.csv") for i in range(1,c)], ignore_index=True).to_csv("movie_duration_from_wikidata.csv", index=False)

In [13]:
import re

durations_df = pd.read_csv("movie_duration_from_wikidata.csv")

counts_durations_df = durations_df["freebaseID"].value_counts()

durations_df[durations_df["freebaseID"].apply(lambda x: counts_durations_df[x] > 1)].head(20)

pattern = r'^Q\d+$'
def merge_labels(labels):
    n = len(labels)
    for i in range(n):
        if not re.match(pattern, labels.iloc[i]):
            return labels.iloc[i]
    return labels.iloc[n-1]

def first(l):
    return l.iloc[0]

def max_skip_na(l):
    return l.dropna().max()

result = durations_df.groupby('freebaseID').agg({
    's': first,
    'sLabel': merge_labels,
    'duration': max_skip_na
})

result = result.reset_index()

In [14]:
movies_df = pd.merge(movie_metadata_df, result, left_on="Freebase movie ID", right_on="freebaseID", how="outer")

movies_df["true_duration"] = movies_df.apply(lambda row: row["Movie runtime"] if pd.notna(row["Movie runtime"]) else row["duration"], axis=1)

print_missing_stats(movies_df)

81741 75376 81741

In [1]:
character_metadata_df["Actor ethnicity (Freebase ID)"].unique()[1:]

basic_query = '''
SELECT ?s ?sLabel ?freebaseID
WHERE {{
  
  VALUES ?freebaseID {{ 
{ids_string}
  }}
  
  ?s wdt:P646 ?freebaseID .
  
  SERVICE wikibase:label {{ bd:serviceParam wikibase:language "en" . }}
  
}}
'''

ids_string = "\n".join(["\"" + x + "\"" for x in character_metadata_df["Actor ethnicity (Freebase ID)"].unique()[1:].astype(str)])

query = basic_query.format(ids_string = ids_string)

print(query)

NameError: name 'character_metadata_df' is not defined

In [10]:
generic_query = '''
SELECT ?s ?sLabel ?freebaseID ?castMember ?castMemberLabel ?character ?characterLabel ?roleLabel
WHERE {
  
  VALUES ?freebaseID { 
|
  }
  
  ?s wdt:P646 ?freebaseID .

  OPTIONAL { 
    ?s p:P161 ?castStatement .
    ?castStatement ps:P161 ?castMember .
    OPTIONAL { ?castStatement pq:P453 ?character }
    OPTIONAL { ?castStatement pq:P4633 ?role }
  }
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }
  
}
'''

n = len(movie_metadata_df)
step = 100

low = 0
c = 1
while low < n:
    up = min(low + step, n)

    ids_string = "\n".join(movie_metadata_df["Freebase movie ID"][low:up].astype(str).apply(lambda x: "\"" + x + "\""))
    query = generic_query.replace("|", ids_string)
    
    success = download_sparql_csv(query, f"tempData/actors_roles_{c:04d}.csv")
    
    if success:
        low = up
        c += 1
        print(f"{up}/{n} done")
    else:
        print(f"{low} - {up} to redo")

pd.concat([pd.read_csv(f"tempData/actors_roles_{i:04d}.csv") for i in range(1,c)], ignore_index=True).to_csv("actors_roles_from_wikidata.csv", index=False)

100/81741 done
200/81741 done
300/81741 done
400/81741 done
500/81741 done
600/81741 done
700/81741 done
800/81741 done
900/81741 done
1000/81741 done
1100/81741 done
1200/81741 done
1300/81741 done
1400/81741 done
1500/81741 done
1600/81741 done
1700/81741 done
1800/81741 done
1900/81741 done
2000/81741 done
2100/81741 done
2200/81741 done
2300/81741 done
2400/81741 done
2500/81741 done
2600/81741 done
2700/81741 done
2800/81741 done
2900/81741 done
3000/81741 done
3100/81741 done
3200/81741 done
3300/81741 done
3400/81741 done
Error: Failed to retrieve data. Status code 429
3400 - 3500 to redo
3500/81741 done
3600/81741 done
3700/81741 done
3800/81741 done
3900/81741 done
4000/81741 done
4100/81741 done
4200/81741 done
4300/81741 done
4400/81741 done
4500/81741 done
4600/81741 done
4700/81741 done
4800/81741 done
4900/81741 done
5000/81741 done
5100/81741 done
5200/81741 done
5300/81741 done
5400/81741 done
5500/81741 done
5600/81741 done
5700/81741 done
5800/81741 done
5900/81741 done
6000/81741 done
6100/81741 done
6200/81741 done
6300/81741 done
6400/81741 done
6500/81741 done
6600/81741 done
6700/81741 done
6800/81741 done
6900/81741 done
7000/81741 done
7100/81741 done
7200/81741 done
7300/81741 done
7400/81741 done
7500/81741 done
7600/81741 done
7700/81741 done
7800/81741 done
7900/81741 done
8000/81741 done
8100/81741 done
8200/81741 done
8300/81741 done
8400/81741 done
8500/81741 done
8600/81741 done
8700/81741 done
8800/81741 done
8900/81741 done
9000/81741 done
9100/81741 done
9200/81741 done
9300/81741 done
9400/81741 done
9500/81741 done
9600/81741 done
9700/81741 done
9800/81741 done
9900/81741 done
10000/81741 done
10100/81741 done
10200/81741 done
10300/81741 done
10400/81741 done
10500/81741 done
10600/81741 done
10700/81741 done
10800/81741 done
10900/81741 done
11000/81741 done
11100/81741 done
11200/81741 done
11300/81741 done
11400/81741 done
11500/81741 done
11600/81741 done
11700/81741 done
11800/81741 done
11900/81741 done
12000/81741 done
12100/81741 done
12200/81741 done
12300/81741 done
12400/81741 done
12500/81741 done
12600/81741 done
12700/81741 done
12800/81741 done
12900/81741 done
13000/81741 done
13100/81741 done
13200/81741 done
13300/81741 done
13400/81741 done
13500/81741 done
13600/81741 done
13700/81741 done
13800/81741 done
13900/81741 done
14000/81741 done
14100/81741 done
14200/81741 done
14300/81741 done
14400/81741 done
14500/81741 done
14600/81741 done
14700/81741 done
14800/81741 done
14900/81741 done
15000/81741 done
15100/81741 done
15200/81741 done
15300/81741 done
15400/81741 done
15500/81741 done
15600/81741 done
Error: Failed to retrieve data. Status code 429
15600 - 15700 to redo
15700/81741 done
15800/81741 done
15900/81741 done
Error: Failed to retrieve data. Status code 429
15900 - 16000 to redo
Error: Failed to retrieve data. Status code 429
15900 - 16000 to redo
Error: Failed to retrieve data. Status code 429
15900 - 16000 to redo
16000/81741 done
Error: Failed to retrieve data. Status code 429
16000 - 16100 to redo
16100/81741 done
16200/81741 done
16300/81741 done
16400/81741 done
16500/81741 done
16600/81741 done
16700/81741 done
16800/81741 done
16900/81741 done
17000/81741 done
17100/81741 done
17200/81741 done
17300/81741 done
17400/81741 done
17500/81741 done
17600/81741 done
17700/81741 done
17800/81741 done
17900/81741 done
18000/81741 done
18100/81741 done
18200/81741 done
18300/81741 done
18400/81741 done
18500/81741 done
18600/81741 done
18700/81741 done
18800/81741 done
18900/81741 done
19000/81741 done
19100/81741 done
19200/81741 done
19300/81741 done
19400/81741 done
19500/81741 done
19600/81741 done
19700/81741 done
19800/81741 done
19900/81741 done
20000/81741 done
20100/81741 done
20200/81741 done
20300/81741 done
20400/81741 done
20500/81741 done
20600/81741 done
20700/81741 done
20800/81741 done
20900/81741 done
21000/81741 done
21100/81741 done
21200/81741 done
21300/81741 done
21400/81741 done
21500/81741 done
21600/81741 done
Error: Failed to retrieve data. Status code 429
21600 - 21700 to redo
Error: Failed to retrieve data. Status code 429
21600 - 21700 to redo
Error: Failed to retrieve data. Status code 429
21600 - 21700 to redo
21700/81741 done
Error: Failed to retrieve data. Status code 429
21700 - 21800 to redo
Error: Failed to retrieve data. Status code 429
21700 - 21800 to redo
21800/81741 done
Error: Failed to retrieve data. Status code 429
21800 - 21900 to redo
21900/81741 done
22000/81741 done
22100/81741 done
Error: Failed to retrieve data. Status code 429
22100 - 22200 to redo
Error: Failed to retrieve data. Status code 429
22100 - 22200 to redo
22200/81741 done
Error: Failed to retrieve data. Status code 429
22200 - 22300 to redo
Error: Failed to retrieve data. Status code 429
22200 - 22300 to redo
Error: Failed to retrieve data. Status code 429
22200 - 22300 to redo
22300/81741 done
Error: Failed to retrieve data. Status code 429
22300 - 22400 to redo
Error: Failed to retrieve data. Status code 429
22300 - 22400 to redo
22400/81741 done
Error: Failed to retrieve data. Status code 429
22400 - 22500 to redo
Error: Failed to retrieve data. Status code 429
22400 - 22500 to redo
22500/81741 done
Error: Failed to retrieve data. Status code 429
22500 - 22600 to redo
Error: Failed to retrieve data. Status code 429
22500 - 22600 to redo
Error: Failed to retrieve data. Status code 429
22500 - 22600 to redo
22600/81741 done
22700/81741 done
Error: Failed to retrieve data. Status code 429
22700 - 22800 to redo
22800/81741 done
Error: Failed to retrieve data. Status code 429
22800 - 22900 to redo
Error: Failed to retrieve data. Status code 429
22800 - 22900 to redo
Error: Failed to retrieve data. Status code 429
22800 - 22900 to redo
22900/81741 done
23000/81741 done
Error: Failed to retrieve data. Status code 429
23000 - 23100 to redo
23100/81741 done
23200/81741 done
23300/81741 done
23400/81741 done
23500/81741 done
23600/81741 done
23700/81741 done
23800/81741 done
23900/81741 done
24000/81741 done
24100/81741 done
Error: Failed to retrieve data. Status code 429
24100 - 24200 to redo
24200/81741 done
Error: Failed to retrieve data. Status code 429
24200 - 24300 to redo
Error: Failed to retrieve data. Status code 429
24200 - 24300 to redo
24300/81741 done
24400/81741 done
24500/81741 done
Error: Failed to retrieve data. Status code 429
24500 - 24600 to redo
Error: Failed to retrieve data. Status code 429
24500 - 24600 to redo
24600/81741 done
Error: Failed to retrieve data. Status code 429
24600 - 24700 to redo
24700/81741 done
Error: Failed to retrieve data. Status code 429
24700 - 24800 to redo
Error: Failed to retrieve data. Status code 429
24700 - 24800 to redo
Error: Failed to retrieve data. Status code 429
24700 - 24800 to redo
24800/81741 done
24900/81741 done
25000/81741 done
25100/81741 done
25200/81741 done
25300/81741 done
25400/81741 done
25500/81741 done
25600/81741 done
25700/81741 done
25800/81741 done
25900/81741 done
26000/81741 done
26100/81741 done
26200/81741 done
26300/81741 done
Error: Failed to retrieve data. Status code 429
26300 - 26400 to redo
Error: Failed to retrieve data. Status code 429
26300 - 26400 to redo
26400/81741 done
Error: Failed to retrieve data. Status code 429
26400 - 26500 to redo
26500/81741 done
26600/81741 done
26700/81741 done
26800/81741 done
26900/81741 done
27000/81741 done
27100/81741 done
27200/81741 done
Error: Failed to retrieve data. Status code 429
27200 - 27300 to redo
27300/81741 done
27400/81741 done
27500/81741 done
27600/81741 done
27700/81741 done
27800/81741 done
27900/81741 done
28000/81741 done
28100/81741 done
28200/81741 done
28300/81741 done
28400/81741 done
28500/81741 done
28600/81741 done
28700/81741 done
28800/81741 done
28900/81741 done
29000/81741 done
29100/81741 done
29200/81741 done
29300/81741 done
29400/81741 done
29500/81741 done
29600/81741 done
29700/81741 done
29800/81741 done
29900/81741 done
30000/81741 done
30100/81741 done
30200/81741 done
30300/81741 done
30400/81741 done
30500/81741 done
30600/81741 done
30700/81741 done
30800/81741 done
30900/81741 done
31000/81741 done
31100/81741 done
Error: Failed to retrieve data. Status code 429
31100 - 31200 to redo
31200/81741 done
Error: Failed to retrieve data. Status code 429
31200 - 31300 to redo
Error: Failed to retrieve data. Status code 429
31200 - 31300 to redo
Error: Failed to retrieve data. Status code 429
31200 - 31300 to redo
31300/81741 done
Error: Failed to retrieve data. Status code 429
31300 - 31400 to redo
31400/81741 done
Error: Failed to retrieve data. Status code 429
31400 - 31500 to redo
Error: Failed to retrieve data. Status code 429
31400 - 31500 to redo
31500/81741 done
31600/81741 done
31700/81741 done
Error: Failed to retrieve data. Status code 429
31700 - 31800 to redo
31800/81741 done
31900/81741 done
32000/81741 done
32100/81741 done
32200/81741 done
Error: Failed to retrieve data. Status code 429
32200 - 32300 to redo
32300/81741 done
Error: Failed to retrieve data. Status code 429
32300 - 32400 to redo
32400/81741 done
32500/81741 done
32600/81741 done
32700/81741 done
32800/81741 done
32900/81741 done
33000/81741 done
33100/81741 done
33200/81741 done
33300/81741 done
33400/81741 done
33500/81741 done
33600/81741 done
Error: Failed to retrieve data. Status code 429
33600 - 33700 to redo
33700/81741 done
33800/81741 done
33900/81741 done
34000/81741 done
34100/81741 done
34200/81741 done
34300/81741 done
34400/81741 done
34500/81741 done
34600/81741 done
34700/81741 done
34800/81741 done
34900/81741 done
35000/81741 done
35100/81741 done
35200/81741 done
35300/81741 done
35400/81741 done
35500/81741 done
35600/81741 done
35700/81741 done
35800/81741 done
35900/81741 done
36000/81741 done
36100/81741 done
36200/81741 done
36300/81741 done
36400/81741 done
36500/81741 done
36600/81741 done
36700/81741 done
36800/81741 done
36900/81741 done
37000/81741 done
37100/81741 done
37200/81741 done
37300/81741 done
37400/81741 done
37500/81741 done
37600/81741 done
37700/81741 done
37800/81741 done
37900/81741 done
38000/81741 done
38100/81741 done
38200/81741 done
38300/81741 done
38400/81741 done
38500/81741 done
38600/81741 done
38700/81741 done
38800/81741 done
38900/81741 done
39000/81741 done
39100/81741 done
39200/81741 done
39300/81741 done
39400/81741 done
39500/81741 done
39600/81741 done
39700/81741 done
39800/81741 done
39900/81741 done
40000/81741 done
40100/81741 done
40200/81741 done
40300/81741 done
40400/81741 done
40500/81741 done
40600/81741 done
40700/81741 done
40800/81741 done
40900/81741 done
41000/81741 done
41100/81741 done
Error: Failed to retrieve data. Status code 429
41100 - 41200 to redo
Error: Failed to retrieve data. Status code 429
41100 - 41200 to redo
41200/81741 done
Error: Failed to retrieve data. Status code 429
41200 - 41300 to redo
Error: Failed to retrieve data. Status code 429
41200 - 41300 to redo
41300/81741 done
Error: Failed to retrieve data. Status code 429
41300 - 41400 to redo
Error: Failed to retrieve data. Status code 429
41300 - 41400 to redo
Error: Failed to retrieve data. Status code 429
41300 - 41400 to redo
41400/81741 done
Error: Failed to retrieve data. Status code 429
41400 - 41500 to redo
Error: Failed to retrieve data. Status code 429
41400 - 41500 to redo
Error: Failed to retrieve data. Status code 429
41400 - 41500 to redo
41500/81741 done
41600/81741 done
Error: Failed to retrieve data. Status code 429
41600 - 41700 to redo
41700/81741 done
Error: Failed to retrieve data. Status code 429
41700 - 41800 to redo
Error: Failed to retrieve data. Status code 429
41700 - 41800 to redo
41800/81741 done
41900/81741 done
42000/81741 done
42100/81741 done
Error: Failed to retrieve data. Status code 429
42100 - 42200 to redo
Error: Failed to retrieve data. Status code 429
42100 - 42200 to redo
42200/81741 done
Error: Failed to retrieve data. Status code 429
42200 - 42300 to redo
Error: Failed to retrieve data. Status code 429
42200 - 42300 to redo
42300/81741 done
42400/81741 done
42500/81741 done
Error: Failed to retrieve data. Status code 429
42500 - 42600 to redo
Error: Failed to retrieve data. Status code 429
42500 - 42600 to redo
42600/81741 done
Error: Failed to retrieve data. Status code 429
42600 - 42700 to redo
Error: Failed to retrieve data. Status code 429
42600 - 42700 to redo
42700/81741 done
42800/81741 done
42900/81741 done
Error: Failed to retrieve data. Status code 429
42900 - 43000 to redo
Error: Failed to retrieve data. Status code 429
42900 - 43000 to redo
43000/81741 done
43100/81741 done
43200/81741 done
43300/81741 done
43400/81741 done
43500/81741 done
43600/81741 done
43700/81741 done
43800/81741 done
43900/81741 done
44000/81741 done
Error: Failed to retrieve data. Status code 429
44000 - 44100 to redo
44100/81741 done
Error: Failed to retrieve data. Status code 429
44100 - 44200 to redo
44200/81741 done
Error: Failed to retrieve data. Status code 429
44200 - 44300 to redo
44300/81741 done
44400/81741 done
Error: Failed to retrieve data. Status code 429
44400 - 44500 to redo
Error: Failed to retrieve data. Status code 429
44400 - 44500 to redo
44500/81741 done
Error: Failed to retrieve data. Status code 429
44500 - 44600 to redo
Error: Failed to retrieve data. Status code 429
44500 - 44600 to redo
44600/81741 done
Error: Failed to retrieve data. Status code 429
44600 - 44700 to redo
44700/81741 done
44800/81741 done
44900/81741 done
45000/81741 done
45100/81741 done
45200/81741 done
45300/81741 done
45400/81741 done
45500/81741 done
45600/81741 done
45700/81741 done
45800/81741 done
45900/81741 done
46000/81741 done
46100/81741 done
46200/81741 done
46300/81741 done
46400/81741 done
46500/81741 done
46600/81741 done
46700/81741 done
46800/81741 done
46900/81741 done
47000/81741 done
47100/81741 done
47200/81741 done
47300/81741 done
Error: Failed to retrieve data. Status code 429
47300 - 47400 to redo
Error: Failed to retrieve data. Status code 429
47300 - 47400 to redo
47400/81741 done
47500/81741 done
47600/81741 done
47700/81741 done
47800/81741 done
47900/81741 done
48000/81741 done
48100/81741 done
48200/81741 done
48300/81741 done
48400/81741 done
48500/81741 done
48600/81741 done
48700/81741 done
48800/81741 done
48900/81741 done
49000/81741 done
49100/81741 done
49200/81741 done
49300/81741 done
49400/81741 done
49500/81741 done
49600/81741 done
Error: Failed to retrieve data. Status code 429
49600 - 49700 to redo
49700/81741 done
49800/81741 done
49900/81741 done
Error: Failed to retrieve data. Status code 429
49900 - 50000 to redo
50000/81741 done
50100/81741 done
50200/81741 done
50300/81741 done
50400/81741 done
50500/81741 done
50600/81741 done
50700/81741 done
50800/81741 done
50900/81741 done
51000/81741 done
51100/81741 done
51200/81741 done
51300/81741 done
Error: Failed to retrieve data. Status code 429
51300 - 51400 to redo
51400/81741 done
51500/81741 done
51600/81741 done
51700/81741 done
51800/81741 done
51900/81741 done
52000/81741 done
52100/81741 done
Error: Failed to retrieve data. Status code 429
52100 - 52200 to redo
52200/81741 done
Error: Failed to retrieve data. Status code 429
52200 - 52300 to redo
Error: Failed to retrieve data. Status code 429
52200 - 52300 to redo
52300/81741 done
Error: Failed to retrieve data. Status code 429
52300 - 52400 to redo
Error: Failed to retrieve data. Status code 429
52300 - 52400 to redo
52400/81741 done
Error: Failed to retrieve data. Status code 429
52400 - 52500 to redo
52500/81741 done
52600/81741 done
Error: Failed to retrieve data. Status code 429
52600 - 52700 to redo
Error: Failed to retrieve data. Status code 429
52600 - 52700 to redo
52700/81741 done
52800/81741 done
Error: Failed to retrieve data. Status code 429
52800 - 52900 to redo
Error: Failed to retrieve data. Status code 429
52800 - 52900 to redo
52900/81741 done
Error: Failed to retrieve data. Status code 429
52900 - 53000 to redo
53000/81741 done
Error: Failed to retrieve data. Status code 429
53000 - 53100 to redo
53100/81741 done
Error: Failed to retrieve data. Status code 429
53100 - 53200 to redo
53200/81741 done
Error: Failed to retrieve data. Status code 429
53200 - 53300 to redo
Error: Failed to retrieve data. Status code 429
53200 - 53300 to redo
Error: Failed to retrieve data. Status code 429
53200 - 53300 to redo
Error: Failed to retrieve data. Status code 429
53200 - 53300 to redo
53300/81741 done
Error: Failed to retrieve data. Status code 429
53300 - 53400 to redo
Error: Failed to retrieve data. Status code 429
53300 - 53400 to redo
53400/81741 done
53500/81741 done
Error: Failed to retrieve data. Status code 429
53500 - 53600 to redo
Error: Failed to retrieve data. Status code 429
53500 - 53600 to redo
53600/81741 done
Error: Failed to retrieve data. Status code 429
53600 - 53700 to redo
53700/81741 done
53800/81741 done
Error: Failed to retrieve data. Status code 429
53800 - 53900 to redo
Error: Failed to retrieve data. Status code 429
53800 - 53900 to redo
Error: Failed to retrieve data. Status code 429
53800 - 53900 to redo
53900/81741 done
54000/81741 done
Error: Failed to retrieve data. Status code 429
54000 - 54100 to redo
Error: Failed to retrieve data. Status code 429
54000 - 54100 to redo
Error: Failed to retrieve data. Status code 429
54000 - 54100 to redo
Error: Failed to retrieve data. Status code 429
54000 - 54100 to redo
54100/81741 done
Error: Failed to retrieve data. Status code 429
54100 - 54200 to redo
Error: Failed to retrieve data. Status code 429
54100 - 54200 to redo
Error: Failed to retrieve data. Status code 429
54100 - 54200 to redo
Error: Failed to retrieve data. Status code 429
54100 - 54200 to redo
54200/81741 done
Error: Failed to retrieve data. Status code 429
54200 - 54300 to redo
Error: Failed to retrieve data. Status code 429
54200 - 54300 to redo
Error: Failed to retrieve data. Status code 429
54200 - 54300 to redo
54300/81741 done
54400/81741 done
54500/81741 done
54600/81741 done
54700/81741 done
54800/81741 done
54900/81741 done
55000/81741 done
55100/81741 done
55200/81741 done
55300/81741 done
55400/81741 done
55500/81741 done
55600/81741 done
55700/81741 done
55800/81741 done
55900/81741 done
56000/81741 done
56100/81741 done
56200/81741 done
56300/81741 done
56400/81741 done
56500/81741 done
56600/81741 done
56700/81741 done
56800/81741 done
56900/81741 done
57000/81741 done
57100/81741 done
57200/81741 done
57300/81741 done
57400/81741 done
57500/81741 done
57600/81741 done
57700/81741 done
57800/81741 done
57900/81741 done
58000/81741 done
58100/81741 done
58200/81741 done
58300/81741 done
58400/81741 done
58500/81741 done
58600/81741 done
58700/81741 done
58800/81741 done
Error: Failed to retrieve data. Status code 429
58800 - 58900 to redo
Error: Failed to retrieve data. Status code 429
58800 - 58900 to redo
58900/81741 done
59000/81741 done
Error: Failed to retrieve data. Status code 429
59000 - 59100 to redo
59100/81741 done
59200/81741 done
59300/81741 done
59400/81741 done
59500/81741 done
59600/81741 done
59700/81741 done
59800/81741 done
59900/81741 done
60000/81741 done
60100/81741 done
60200/81741 done
60300/81741 done
60400/81741 done
60500/81741 done
60600/81741 done
60700/81741 done
60800/81741 done
60900/81741 done
61000/81741 done
61100/81741 done
61200/81741 done
61300/81741 done
61400/81741 done
61500/81741 done
61600/81741 done
61700/81741 done
61800/81741 done
61900/81741 done
62000/81741 done
62100/81741 done
62200/81741 done
62300/81741 done
62400/81741 done
62500/81741 done
62600/81741 done
62700/81741 done
62800/81741 done
62900/81741 done
63000/81741 done
63100/81741 done
63200/81741 done
63300/81741 done
63400/81741 done
63500/81741 done
63600/81741 done
63700/81741 done
63800/81741 done
63900/81741 done
64000/81741 done
64100/81741 done
64200/81741 done
64300/81741 done
64400/81741 done
64500/81741 done
64600/81741 done
64700/81741 done
64800/81741 done
64900/81741 done
65000/81741 done
65100/81741 done
65200/81741 done
65300/81741 done
65400/81741 done
65500/81741 done

FileNotFoundError: [Errno 2] No such file or directory: 'AdditionalData/actors_roles_0001.csv'

In [35]:
from fuzzywuzzy import fuzz

def names_similarity(str1, str2):
    return fuzz.ratio(str1.lower(), str2.lower())/100.

In [42]:
def time_to_minutes(time_string):
    hours = 0
    minutes = 0
    
    time_parts = time_string.split()

    for part in time_parts:
        if 'h' in part:
            hours = int(part.replace('h', ''))
        if 'm' in part:
            minutes = int(part.replace('m', ''))

    total_minutes = hours * 60 + minutes
    return total_minutes

def safe_int_conversion(value, default):
    try:
        return int(value)
    except ValueError:
        return default

In [46]:
import requests
from bs4 import BeautifulSoup

def get_rotten_url_from_movie_name(movie_name, year = None, toll = 0.8):
    r = requests.get("https://www.rottentomatoes.com/search?search=" + requests.utils.quote(movie_name, safe=''))
    soup = BeautifulSoup(r.content, 'html.parser')
    movies = soup.find_all('search-page-media-row')
    movie_list = []
    
    for movie in movies:
        title_tag = movie.find('a', {'slot': 'title'})
        title = title_tag.get_text(strip=True) if title_tag else ''
        
        release_year = safe_int_conversion(movie.get('releaseyear', ''), None)
        
        link = title_tag.get('href') if title_tag else ''
        
        movie_list.append((title, release_year, link))

    best_match = dict()
    best_match['toll'] = toll
    best_match['movie'] = (None, None, None)
    for movie in movie_list:
        similarity = names_similarity(movie[0], movie_name)
        if similarity > best_match['toll'] and (year is None or movie[1] is None or abs(movie[1] - year) <= 1):
            best_match['toll'] = similarity
            best_match['movie'] = movie
    return best_match['movie'][2]

print(get_rotten_url_from_movie_name("The Sorcerer's Apprentice", 2001))

https://www.rottentomatoes.com/m/1170191-sorcerers_apprentice

In [61]:

def get_rotten_movie_metadata(url, toll = 0.95):
    movie_metadata = dict()
    
    if url is None:
        return movie_metadata
    r = requests.get(url)
    soup = BeautifulSoup(r.content, "html.parser")
    
    movie_metadata["title"] = soup.find('rt-text', {'slot': 'title'}).get_text(strip=True)
    
    critics_score_string = soup.find('rt-button', {'slot': 'criticsScore'}).find('rt-text').get_text(strip=True).replace("%","")
    movie_metadata["critics_score"] = safe_int_conversion(critics_score_string, None)
    audience_score_string = soup.find('rt-button', {'slot': 'audienceScore'}).find('rt-text').get_text(strip=True).replace("%","")
    movie_metadata["audience_score"] = safe_int_conversion(audience_score_string, None)
    
    category_wraps = soup.find_all('div', {'class': 'category-wrap', 'data-qa': 'item'})
    for wrap in category_wraps:
        wrap_title = wrap.find('rt-text', {'class': 'key'}).get_text(strip=True)
        
        if names_similarity(wrap_title, "Rating") > toll:
            movie_metadata["rating"] = wrap.find(['rt-text', 'rt-link'], {'data-qa': 'item-value'}).get_text(strip=True)
        if names_similarity(wrap_title, "Genre") > toll:
            movie_metadata["genre"] = wrap.find(['rt-text', 'rt-link'], {'data-qa': 'item-value'}).get_text(strip=True)
        if names_similarity(wrap_title, "Original Language") > toll:
            movie_metadata["language"] = wrap.find(['rt-text', 'rt-link'], {'data-qa': 'item-value'}).get_text(strip=True)
        if names_similarity(wrap_title, "Runtime") > toll:
            runtime_string = wrap.find(['rt-text', 'rt-link'], {'data-qa': 'item-value'}).get_text(strip=True)
            movie_metadata["runtime"] = time_to_minutes(runtime_string)
    
    return movie_metadata

for i in range(50):
    row = movie_metadata_df.iloc[i]

    movie_title = row["Movie name"]
    if pd.notna(row["Movie release date"]):
        year = safe_int_conversion(row["Movie release date"].split('-')[0], None)
    else:
        year = None
    
    print(movie_title, year)
    print(get_rotten_movie_metadata(get_rotten_url_from_movie_name(movie_title, year)))

Ghosts of Mars 2001
{}
Getting Away with Murder: The JonBenét Ramsey Mystery 2000
{}
Brun bitter 1988
{}
White Of The Eye 1987
{'title': 'White of the Eye', 'critics_score': 50, 'audience_score': 57, 'rating': 'R', 'genre': 'Mystery & Thriller', 'language': 'English', 'runtime': 110}
A Woman in Flames 1983
{'title': 'A Woman in Flames', 'critics_score': None, 'audience_score': 62, 'genre': 'Drama', 'language': 'German', 'runtime': 107}
The Gangsters 1913
{}
The Sorcerer's Apprentice 2002
{'title': "The Sorcerer's Apprentice", 'critics_score': None, 'audience_score': 32, 'genre': 'Fantasy', 'language': 'English', 'runtime': 89}
Alexander's Ragtime Band 1938
{'title': "Alexander's Ragtime Band", 'critics_score': 83, 'audience_score': 46, 'genre': 'Musical', 'language': 'English', 'runtime': 105}
Contigo y aquí 1974
{}
City of the Dead 1960
{}
Sarah and Son 1930
{'title': 'Sarah and Son', 'critics_score': None, 'audience_score': 22, 'genre': 'Drama', 'language': 'English', 'runtime': 86}
Lady Snowblood 2: Love Song of Vengeance 1974
{'title': 'Lady Snowblood 2: Love Song of Vengeance', 'critics_score': None, 'audience_score': 59, 'genre': 'Drama', 'language': 'Japanese', 'runtime': 89}
Little city 1997
{'title': 'Little City', 'critics_score': None, 'audience_score': 64, 'rating': 'R', 'genre': 'Romance', 'language': 'English', 'runtime': 89}
Henry V 1989
{'title': 'Henry V', 'critics_score': 98, 'audience_score': 89, 'rating': 'PG-13 (A Bloody Battle)', 'genre': 'History', 'language': 'English', 'runtime': 137}
Aaah Belinda 1986
{}
The Mechanical Monsters None
{'title': 'The Mechanical Universe', 'critics_score': None, 'audience_score': None, 'rating': 'TV-G', 'genre': 'Special Interest', 'language': 'English'}
1919 1984
{'title': '1919', 'critics_score': None, 'audience_score': None, 'genre': 'Drama', 'language': 'English', 'runtime': 99}
Mary Poppins 1964
{'title': 'Mary Poppins', 'critics_score': 97, 'audience_score': 86, 'rating': 'G', 'genre': 'Kids & Family', 'language': 'English', 'runtime': 140}
Die Fahne von Kriwoj Rog 1967
{}
Keep the Change 1992
{'title': 'Keep the Change', 'critics_score': None, 'audience_score': 60, 'rating': 'TV-PG', 'genre': 'Western', 'language': 'English', 'runtime': 100}
The Devil's Holiday 1930
{'title': "The Devil's Holiday", 'critics_score': None, 'audience_score': 25, 'genre': 'Drama', 'language': 'English', 'runtime': 80}
New Rose Hotel 1999
{'title': 'New Rose Hotel', 'critics_score': 24, 'audience_score': 38, 'rating': 'R', 'genre': 'Drama', 'language': 'English', 'runtime': 92}
White on Rice 2009
{'title': 'White on Rice', 'critics_score': 45, 'audience_score': 52, 'rating': 'PG-13 (Sex-Related Humor|Some Violent Images)', 'genre': 'Comedy', 'language': 'English', 'runtime': 90}
Freddy and the Song of the South Pacific 1962
{}
Road to Life 1931
{'title': 'Road to Life', 'critics_score': None, 'audience_score': None, 'genre': 'Drama', 'language': 'Russian', 'runtime': 98}
Camera Thrills 1935
{'title': 'Camera Thrills', 'critics_score': None, 'audience_score': None, 'genre': 'Documentary', 'language': 'English', 'runtime': 25}
Ferdinando I, re di Napoli 1959
{}
Anbu Thozhi 2007
{}
Middle Age Spread 1979
{'title': 'Middle Age Spread', 'critics_score': None, 'audience_score': None, 'genre': 'Comedy', 'language': 'English', 'runtime': 94}
Baby Boy 2001
{'title': 'Baby Boy', 'critics_score': 71, 'audience_score': 87, 'rating': 'R (Some Drug Use|Language|Strong Sexuality|Violence)', 'genre': 'Drama', 'language': 'English', 'runtime': 129}
Bindiya Chamkegi 1984
{'title': 'Bindiya Chamkegi', 'critics_score': None, 'audience_score': None, 'genre': 'Comedy', 'language': 'Hindi', 'runtime': 139}
Vandanam 1989
{'title': 'Vandhanam', 'critics_score': None, 'audience_score': None, 'genre': 'Romance', 'language': 'Malayalam', 'runtime': 179}
Emilia Galotti 1958
{}
Special Effects 1984
{'title': 'Special Effects', 'critics_score': None, 'audience_score': None, 'rating': 'R', 'genre': 'Mystery & Thriller', 'language': 'English', 'runtime': 93}
El Misterioso señor Marquina 1943
{}
Anokha Rishta 1986
{'title': 'Anokha Rishta', 'critics_score': None, 'audience_score': None, 'genre': 'Drama', 'language': 'Hindi'}
They Knew What They Wanted 1940
{'title': 'They Knew What They Wanted', 'critics_score': None, 'audience_score': 40, 'genre': 'Drama', 'language': 'English', 'runtime': 96}
Karayilekku Oru Kadal Dooram 2010
{}
Siam Sunset 1999
{'title': 'Siam Sunset', 'critics_score': 67, 'audience_score': 60, 'genre': 'Comedy', 'language': 'English', 'runtime': 91}
Kausthubham 2010
{'title': 'Kausthubham', 'critics_score': None, 'audience_score': None, 'genre': 'Drama', 'language': 'Malayalam', 'runtime': 180}
Cuando los duendes cazan perdices 1955
{}
Archie: To Riverdale and Back Again 1990
{'title': 'Archie: To Riverdale and Back Again', 'critics_score': None, 'audience_score': 44, 'rating': 'PG', 'genre': 'Comedy', 'language': 'English', 'runtime': 96}
Vinayaka Geleyara Balaga 2011
{}
Mysterious Island 1982
{'title': 'Mysterious Islands', 'critics_score': None, 'audience_score': None, 'rating': 'TV-G', 'genre': 'Travel', 'language': 'English'}
Woman Hungry 1930
{}
Electric Apricot: Quest For Festeroo 2006
{'title': 'Electric Apricot: Quest for Festeroo', 'critics_score': None, 'audience_score': 72, 'rating': 'R (Language|Some Sexual Content Incl Ref)', 'genre': 'Comedy', 'language': 'English', 'runtime': 91}
Troops 1997
{'title': 'Troopers', 'critics_score': None, 'audience_score': None, 'rating': 'TV-14', 'genre': 'Documentary', 'language': 'English'}
Daddy and Them 2001
{'title': 'Daddy and Them', 'critics_score': 86, 'audience_score': 54, 'rating': 'R (Strong Language)', 'genre': 'Comedy', 'language': 'English', 'runtime': 101}
The Sky Pirate 1914
{}
The Gods Must Be Crazy 1980
{'title': 'The Gods Must Be Crazy', 'critics_score': 86, 'audience_score': 84, 'rating': 'PG', 'genre': 'Comedy', 'language': 'Afrikaans', 'runtime': 108}