# Preliminary analysis of Movies Dataset

In [1]:
import os
while os.path.basename(os.getcwd()) != "ada-project-private":
    os.chdir('..')

import pandas as pd
import json

DATA_FOLDER = './MovieSummaries/'

# Load character.metadata.tsv
character_metadata_cols = ["Wikipedia movie ID", "Freebase movie ID",
                           "Movie release date", "Character name",
                           "Actor date of birth", "Actor gender", "Actor height (in meters)", "Actor ethnicity (Freebase ID)",
                           "Actor name", "Actor age at movie release",
                           "Freebase character/actor map ID", "Freebase character ID", "Freebase actor ID"]
character_metadata_df = pd.read_csv(DATA_FOLDER + 'character.metadata.tsv', sep='\t', header=None, names=character_metadata_cols)

# Load movie.metadata.tsv
movie_metadata_cols = ["Wikipedia movie ID", "Freebase movie ID", "Movie name", "Movie release date", "Movie box office revenue", "Movie runtime",
                       "Movie languages (Freebase ID:name tuples)", "Movie countries (Freebase ID:name tuples)",
                       "Movie genres (Freebase ID:name tuples)"]
movie_metadata_df = pd.read_csv(DATA_FOLDER + 'movie.metadata.tsv', sep='\t', header=None, names=movie_metadata_cols)

# Load name.clusters.txt
name_clusters_cols = ["Character name", "Freebase movie ID"]
name_clusters_df = pd.read_csv(DATA_FOLDER + 'name.clusters.txt', sep='\t', header=None, names=name_clusters_cols)

# Load plot_summaries.txt
plot_summaries_cols = ["Wikipedia movie ID", "Wikipedia plot"]
plot_summaries_df = pd.read_csv(DATA_FOLDER + 'plot_summaries.txt', sep='\t', header=None, names=plot_summaries_cols)

# Load tvtropes.clusters.txt
tvtropes_clusters_cols = ["Character types", "details"]
tvtropes_clusters_df = pd.read_csv(DATA_FOLDER + 'tvtropes.clusters.txt', sep='\t', header=None, names=tvtropes_clusters_cols)

tvtropes_clusters_df["details_dict"] = tvtropes_clusters_df["details"].apply(json.loads)
tvtropes_clusters_df["Character name"] = tvtropes_clusters_df["details_dict"].apply(lambda x: x.get('char'))
tvtropes_clusters_df["Movie name"] = tvtropes_clusters_df["details_dict"].apply(lambda x: x.get('movie'))
tvtropes_clusters_df["Freebase character/actor map ID"] = tvtropes_clusters_df["details_dict"].apply(lambda x: x.get('id'))
tvtropes_clusters_df["Actor name"] = tvtropes_clusters_df["details_dict"].apply(lambda x: x.get('actor'))

tvtropes_clusters_df.drop(columns=["details", "details_dict"], inplace=True)

In [2]:
def print_missing_stats(df):
    print("total len:", len(df))
    for col in df.columns:
        print("missing " + col + ":", sum(df[col].isna()))

In [17]:
print_missing_stats(character_metadata_df)

print("")
print("missing Freebase actor ID but not Actor name:", sum(character_metadata_df["Freebase actor ID"].isna() & character_metadata_df["Actor name"].notna()))
print("We drop all the rows that have NA in the column \"Freebase actor ID\"")
character_metadata_df = character_metadata_df.dropna(subset=["Freebase actor ID"])

print("")
print_missing_stats(character_metadata_df)

character_metadata_df[character_metadata_df["Freebase movie ID"] == "/m/03vyhn"].head()

total len: 449854
missing Wikipedia movie ID: 0
missing Freebase movie ID: 0
missing Movie release date: 9980
missing Character name: 257389
missing Actor date of birth: 105330
missing Actor gender: 44794
missing Actor height (in meters): 295030
missing Actor ethnicity (Freebase ID): 343796
missing Actor name: 413
missing Actor age at movie release: 157298
missing Freebase character/actor map ID: 0
missing Freebase character ID: 257379
missing Freebase actor ID: 0

missing Freebase actor ID but not Actor name: 0
We drop all the rows that have NA in the column "Freebase actor ID"

total len: 449854
missing Wikipedia movie ID: 0
missing Freebase movie ID: 0
missing Movie release date: 9980
missing Character name: 257389
missing Actor date of birth: 105330
missing Actor gender: 44794
missing Actor height (in meters): 295030
missing Actor ethnicity (Freebase ID): 343796
missing Actor name: 413
missing Actor age at movie release: 157298
missing Freebase character/actor map ID: 0
missing Freebase character ID: 257379
missing Freebase actor ID: 0

,Wikipedia movie ID,Freebase movie ID,Movie release date,Character name,Actor date of birth,Actor gender,Actor height (in meters),Actor ethnicity (Freebase ID),Actor name,Actor age at movie release,Freebase character/actor map ID,Freebase character ID,Freebase actor ID
0,975900,/m/03vyhn,2001-08-24,Akooshay,1958-08-26,F,1.620,NaN,Wanda De Jesus,42.0,/m/0bgchxw,/m/0bgcj3x,/m/03wcfv7
1,975900,/m/03vyhn,2001-08-24,Lieutenant Melanie Ballard,1974-08-15,F,1.780,/m/044038p,Natasha Henstridge,27.0,/m/0jys3m,/m/0bgchn4,/m/0346l4
2,975900,/m/03vyhn,2001-08-24,Desolation Williams,1969-06-15,M,1.727,/m/0x67,Ice Cube,32.0,/m/0jys3g,/m/0bgchn_,/m/01vw26l
3,975900,/m/03vyhn,2001-08-24,Sgt Jericho Butler,1967-09-12,M,1.750,NaN,Jason Statham,33.0,/m/02vchl6,/m/0bgchnq,/m/034hyc
4,975900,/m/03vyhn,2001-08-24,Bashira Kincaid,1977-09-25,F,1.650,NaN,Clea DuVall,23.0,/m/02vbb3r,/m/0bgchp9,/m/01y9xg

In [15]:
print_missing_stats(movie_metadata_df)

movie_metadata_df.head(10)

total len: 81741
missing Wikipedia movie ID: 0
missing Freebase movie ID: 0
missing Movie name: 0
missing Movie release date: 6902
missing Movie box office revenue: 73340
missing Movie runtime: 20450
missing Movie languages (Freebase ID:name tuples): 0
missing Movie countries (Freebase ID:name tuples): 0
missing Movie genres (Freebase ID:name tuples): 0

,Wikipedia movie ID,Freebase movie ID,Movie name,Movie release date,Movie box office revenue,Movie runtime,Movie languages (Freebase ID:name tuples),Movie countries (Freebase ID:name tuples),Movie genres (Freebase ID:name tuples)
0,975900,/m/03vyhn,Ghosts of Mars,2001-08-24,14010832.0,98.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/01jfsb"": ""Thriller"", ""/m/06n90"": ""Science..."
1,3196793,/m/08yl5d,Getting Away with Murder: The JonBenét Ramsey ...,2000-02-16,NaN,95.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/02n4kr"": ""Mystery"", ""/m/03bxz7"": ""Biograp..."
2,28463795,/m/0crgdbh,Brun bitter,1988,NaN,83.0,"{""/m/05f_3"": ""Norwegian Language""}","{""/m/05b4w"": ""Norway""}","{""/m/0lsxr"": ""Crime Fiction"", ""/m/07s9rl0"": ""D..."
3,9363483,/m/0285_cd,White Of The Eye,1987,NaN,110.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/01jfsb"": ""Thriller"", ""/m/0glj9q"": ""Erotic..."
4,261236,/m/01mrr1,A Woman in Flames,1983,NaN,106.0,"{""/m/04306rv"": ""German Language""}","{""/m/0345h"": ""Germany""}","{""/m/07s9rl0"": ""Drama""}"
5,13696889,/m/03cfc81,The Gangsters,1913-05-29,NaN,35.0,"{""/m/06ppq"": ""Silent film"", ""/m/02h40lc"": ""Eng...","{""/m/09c7w0"": ""United States of America""}","{""/m/02hmvc"": ""Short Film"", ""/m/06ppq"": ""Silen..."
6,18998739,/m/04jcqvw,The Sorcerer's Apprentice,2002,NaN,86.0,"{""/m/02h40lc"": ""English Language""}","{""/m/0hzlz"": ""South Africa""}","{""/m/0hqxf"": ""Family Film"", ""/m/01hmnh"": ""Fant..."
7,10408933,/m/02qc0j7,Alexander's Ragtime Band,1938-08-16,3600000.0,106.0,"{""/m/02h40lc"": ""English Language""}","{""/m/09c7w0"": ""United States of America""}","{""/m/04t36"": ""Musical"", ""/m/01z4y"": ""Comedy"", ..."
8,9997961,/m/06_y2j7,Contigo y aquí,1974,NaN,NaN,"{""/m/06nm1"": ""Spanish Language""}","{""/m/0jgd"": ""Argentina""}","{""/m/04t36"": ""Musical"", ""/m/07s9rl0"": ""Drama"",..."
9,2345652,/m/075f66,City of the Dead,1960,NaN,76.0,"{""/m/02h40lc"": ""English Language""}","{""/m/07ssc"": ""United Kingdom""}","{""/m/03npn"": ""Horror"", ""/m/0fdjb"": ""Supernatur..."

In [5]:
print("total len:", len(plot_summaries_df))

# plot_summaries_df.head(10)

total len: 42303

SELECT ?s ?sLabel ?freebaseID ?duration
WHERE {
  
  VALUES ?freebaseID { 
    "/m/03vyhn" 
    "/m/0crgdbh" 
  }
  
  ?s wdt:P646 ?freebaseID .
  
  OPTIONAL { ?s wdt:P2047 ?duration }
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }
  
}

In [6]:
import requests

def download_sparql_csv(query, file_path):
    url = 'https://query.wikidata.org/sparql'
    
    response = requests.get(url, params={'query': query}, headers={'Accept': 'text/csv'})
    
    if response.status_code == 200:
        with open(file_path, 'wb') as file:
            file.write(response.content)
        return True
    else:
        print(f"Error: Failed to retrieve data. Status code {response.status_code}")
        return False

In [7]:
generic_query = '''
SELECT ?s ?sLabel ?freebaseID ?duration
WHERE {
  VALUES ?freebaseID {
|
  }
  
  ?s wdt:P646 ?freebaseID .
  
  OPTIONAL { ?s wdt:P2047 ?duration }
  
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }
}
'''

In [8]:
# n = len(movie_metadata_df)
# step = 100

# low = 0
# c = 1
# while low < n:
#     up = min(low + step, n)

#     ids_string = "\n".join(movie_metadata_df["Freebase movie ID"][low:up].astype(str).apply(lambda x: "\"" + x + "\""))
#     query = generic_query.replace("|",ids_string)
    
#     success = download_sparql_csv(query, f"AdditionalData/duration_{c:04d}.csv")
    
#     if success:
#         low = up
#         c += 1
    
#     print(f"{up}/{n} done")

# pd.concat([pd.read_csv(f"AdditionalData/duration_{i:04d}.csv") for i in range(1,c)], ignore_index=True).to_csv("movie_duration_from_wikidata.csv", index=False)

In [13]:
import re

durations_df = pd.read_csv("movie_duration_from_wikidata.csv")

counts_durations_df = durations_df["freebaseID"].value_counts()

durations_df[durations_df["freebaseID"].apply(lambda x: counts_durations_df[x] > 1)].head(20)

pattern = r'^Q\d+$'
def merge_labels(labels):
    n = len(labels)
    for i in range(n):
        if not re.match(pattern, labels.iloc[i]):
            return labels.iloc[i]
    return labels.iloc[n-1]

def first(l):
    return l.iloc[0]

def max_skip_na(l):
    return l.dropna().max()

result = durations_df.groupby('freebaseID').agg({
    's': first,
    'sLabel': merge_labels,
    'duration': max_skip_na
})

result = result.reset_index()

In [14]:
movies_df = pd.merge(movie_metadata_df, result, left_on="Freebase movie ID", right_on="freebaseID", how="outer")

movies_df["true_duration"] = movies_df.apply(lambda row: row["Movie runtime"] if pd.notna(row["Movie runtime"]) else row["duration"], axis=1)

print_missing_stats(movies_df)

81741 75376 81741

In [27]:
character_metadata_df["Actor ethnicity (Freebase ID)"].unique()[1:]

basic_query = '''
SELECT ?s ?sLabel ?freebaseID
WHERE {{
  
  VALUES ?freebaseID {{ 
{ids_string}
  }}
  
  ?s wdt:P646 ?freebaseID .
  
  SERVICE wikibase:label {{ bd:serviceParam wikibase:language "en" . }}
  
}}
'''

ids_string = "\n".join(["\"" + x + "\"" for x in character_metadata_df["Actor ethnicity (Freebase ID)"].unique()[1:].astype(str)])

query = basic_query.format(ids_string = ids_string)

print(query)

SELECT ?s ?sLabel ?freebaseID
WHERE {

  VALUES ?freebaseID {
"/m/044038p"
"/m/0x67"
"/m/064b9n"
"/m/041rx"
"/m/033tf_"
"/m/04gfy7"
"/m/0222qb"
"/m/01qhm_"
"/m/0dryh9k"
"/m/048sp5"
"/m/04mvp8"
"/m/0bzkm2"
"/m/02p1pl6"
"/m/0bjbszh"
"/m/022fdt"
"/m/0cqgdq"
"/m/0ffkb4"
"/m/075dhf0"
"/m/01hwt"
"/m/0xnvg"
"/m/0dqqwy"
"/m/048z7l"
"/m/07bch9"
"/m/09v5bdn"
"/m/02w7gg"
"/m/03bkbh"
"/m/02vsw1"
"/m/09kr66"
"/m/09vc4s"
"/m/0g0x7_"
"/m/042gtr"
"/m/0cm7w1"
"/m/046cwm"
"/m/04dbw3"
"/m/02ctzb"
"/m/0g8_vp"
"/m/092h2qt"
"/m/0g6ff"
"/m/0278pqj"
"/m/0301y_"
"/m/019kn7"
"/m/0cnvdq1"
"/m/03295l"
"/m/065b6q"
"/m/03pqwy"
"/m/01xhh5"
"/m/03ts0c"
"/m/06gbnc"
"/m/07hwkr"
"/m/0bpjh3"
"/m/0fpjs3j"
"/m/04nrnz"
"/m/09k5jvk"
"/m/07mqps"
"/m/08hpk0"
"/m/03ttfc"
"/m/0d9q7j"
"/m/075_n6"
"/m/0dllcfn"
"/m/04kbvpz"
"/m/03ftx7"
"/m/0747611"
"/m/025rpb0"
"/m/06mvq"
"/m/047l_90"
"/m/029f2r"
"/m/01rv7x"
"/m/05sf2x"
"/m/01336l"
"/m/0bh91q8"
"/m/01g7zj"
"/m/0cn68"
"/m/02sch9"
"/m/0fqp6zk"
"/m/02y_9mh"
"/m/0d7wh"
"/m/0g96wd"
"/m/047948f"
"/m/04ggbzy"
"/m/04q7gbh"
"/m/013xrm"
"/m/0gkxl2"
"/m/0dbxy"
"/m/0cmdl5l"
"/m/0268d21"
"/m/0912ll"
"/m/022dp5"
"/m/019lrz"
"/m/03bx0k4"
"/m/02p_gby"
"/m/012c1l"
"/m/04y29"
"/m/09743"
"/m/03w9bjf"
"/m/09m6hr"
"/m/0583cz"
"/m/02g7sp"
"/m/063k3h"
"/m/071x0k"
"/m/0bhsnb"
"/m/0bkbz"
"/m/0f0gt_"
"/m/0283js_"
"/m/01kg2v"
"/m/0828vj"
"/m/08v2k7"
"/m/03gskx0"
"/m/0h2138"
"/m/0fng3k"
"/m/023mqw"
"/m/0222hg"
"/m/09vmyh"
"/m/06fczy"
"/m/03lmx1"
"/m/03vv99"
"/m/09zyn5"
"/m/0470lk"
"/m/0fj1k9"
"/m/03cbkrf"
"/m/0bbz66j"
"/m/0268_k"
"/m/04dzwby"
"/m/04y8_bm"
"/m/0ffhz3"
"/m/0ffj5g"
"/m/06j2v"
"/m/03cjjy0"
"/m/06v41q"
"/m/032j30"
"/m/01n94b"
"/m/0d2by"
"/m/038723"
"/m/0g5y6"
"/m/09cqth"
"/m/0bymc"
"/m/0d8qh0"
"/m/0c2hxm"
"/m/04znbg"
"/m/027n1m6"
"/m/02czfr"
"/m/0g48m4"
"/m/01swvz"
"/m/04tvpv"
"/m/0462jl6"
"/m/025_0f0"
"/m/0j6x8"
"/m/05ysft4"
"/m/01ylpf"
"/m/0bnzjx"
"/m/04f581"
"/m/0ch3pqf"
"/m/02p4q5p"
"/m/02wcbj_"
"/m/02jvpv"
"/m/08gzsf"
"/m/02p444n"
"/m/07j80c"
"/m/0btrm4"
"/m/04608z"
"/m/065z7w_"
"/m/0b0gzf"
"/m/033njm"
"/m/02rbdlq"
"/m/01xttr"
"/m/062_25"
"/m/01nbcy"
"/m/02cm28"
"/m/0bns36b"
"/m/0fqz6"
"/m/047bp1r"
"/m/0bs7l_v"
"/m/02qv_h_"
"/m/0dv5vw"
"/m/026c9dq"
"/m/0b__fv3"
"/m/018s6c"
"/m/03yk6g"
"/m/05l3g_"
"/m/0ckk60"
"/m/0bfjm7"
"/m/04jq32s"
"/m/0790v"
"/m/01trsl"
"/m/03cdk7b"
"/m/02q206y"
"/m/05g0f1"
"/m/067lwk"
"/m/05748"
"/m/033qxt"
"/m/097nms"
"/m/04czx7"
"/m/08xbxs"
"/m/0432mrk"
"/m/059_w"
"/m/01ywdy"
"/m/0289z8v"
"/m/013b6_"
"/m/03f3sf"
"/m/017sq0"
"/m/04_hr_"
"/m/071drf"
"/m/0hbz9xw"
"/m/01j2qv"
"/m/0640_7q"
"/m/02p656s"
"/m/0dj8k3"
"/m/0466nw8"
"/m/07d_p8"
"/m/078vc"
"/m/09gp4"
"/m/06lshc"
"/m/0404kdr"
"/m/016f5d"
"/m/04mmhj"
"/m/067lts"
"/m/0761bp"
"/m/0bbcnlt"
"/m/06rd7"
"/m/095mw2"
"/m/09y7x4"
"/m/08cjt2"
"/m/013s3n"
"/m/0g4pffv"
"/m/09gk_6h"
"/m/034s7b"
"/m/0987ctr"
"/m/04_bc8"
"/m/0b98sy"
"/m/0ffjqy"
"/m/0fk1z"
"/m/074w_m"
"/m/03cl2pz"
"/m/07gzw5"
"/m/086wp0"
"/m/01g0y_"
"/m/04k02l"
"/m/02p7gyv"
"/m/03sx6v"
"/m/0bfrrj"
"/m/02pzb09"
"/m/052r3t"
"/m/0268pvf"
"/m/013s2p"
"/m/09chmw"
"/m/0ft9bs"
"/m/013b7g"
"/m/02r_qms"
"/m/0cx3p"
"/m/026cybk"
"/m/04ydrsn"
"/m/067lrj"
"/m/0c3wsgg"
"/m/04zjjt"
"/m/0180zw"
"/m/0hj35"
"/m/025tvhm"
"/m/01p7s6"
"/m/02rp50t"
"/m/025x6k1"
"/m/0150zs"
"/m/0j4w_"
"/m/04l_pt"
"/m/0br_8h"
"/m/0266mf0"
"/m/03cnzsg"
"/m/04hlx1"
"/m/0288fw3"
"/m/02vkw95"
"/m/0fq6zlv"
"/m/01sq7s"
"/m/03r_k"
"/m/0fk3s"
"/m/046j25"
"/m/0338zd"
"/m/027lf0d"
"/m/0152s7"
"/m/03d19xz"
"/m/0520604"
"/m/04_tz7"
"/m/01vsch"
"/m/01d7kx"
"/m/051wcch"
"/m/09lz9zx"
"/m/0738n4"
"/m/0ffjvd"
"/m/051x6yk"
"/m/05sycg"
"/m/0fp54b"
"/m/027vy0s"
"/m/0gf5k1"
"/m/0dc58y8"
"/m/07g8yp"
"/m/0444sm4"
"/m/0318mh"
"/m/07hyjp"
"/m/01c034"
"/m/09fqz7"
"/m/03ndvw"
"/m/0b79c7"
"/m/0665pp"
"/m/03d26m9"
"/m/04lhn7b"
"/m/03h1dq9"
"/m/0152wh"
"/m/0cc5y74"
"/m/0960kn"
"/m/012f86"
"/m/0h6mqq9"
"/m/03wbmrc"
"/m/0dqrh8"
"/m/07n8wy"
"/m/01267"
"/m/01mw1s"
"/m/02gx2x"
"/m/03x_lpj"
"/m/02rm7_9"
"/m/04csgrq"
"/m/05qb937"
"/m/0xff"
"/m/05vhv7"
"/m/078ds"
"/m/0dq1q"
"/m/04wy6k"
"/m/03vghh"
"/m/065577s"
"/m/0463n9y"
"/m/0d32d1"
"/m/0c41n"
"/m/03ck8x1"
"/m/09snp5"
"/m/0fxmtg"
"/m/02r11hz"
"/m/0268xtg"
"/m/026kx7g"
"/m/09tqq8q"
"/m/03kbr"
"/m/05c60ml"
"/m/05mtdy"
"/m/064pj"
"/m/026zlyd"
"/m/08yg47"
"/m/03x_fq7"
"/m/06k6sl"
"/m/0b8yvr"
"/m/01tyl3"
"/m/04sfz4s"
"/m/02vkd28"
"/m/0647lm"
"/m/0bvnws"
"/m/07lv5x"
"/m/02r3wfk"
"/m/02qv716"
"/m/0h8mzsl"
"/m/01nft3"
"/m/031_sd"
"/m/0ffhvl"
"/m/07s49c2"
"/m/03hf_6z"
"/m/0d8qls"
"/m/03fk0c"
"/m/01crfj"
"/m/0h1nk0k"
"/m/01flqq"
"/m/021pd"
"/m/0bms44"
"/m/07s9g04"
"/m/03ty8_"
"/m/02rdfpy"
"/m/02vys3l"
"/m/03fvrb"
"/m/04pnf"
"/m/0bvjpj"
"/m/039z49"
"/m/01_5cg"
"/m/03q819"
"/m/025xss1"
"/m/0c29q8"
"/m/013s41"
"/m/03x1x"
"/m/05cc9h"
"/m/03m9my8"
"/m/0165md"
"/m/0g44f5"
"/m/0gtwjz6"
"/m/01hm_"
"/m/03zcwh"
"/m/04lgl9t"
"/m/0g5k7qv"
"/m/067lv3"
"/m/0ftlzz"
"/m/06y24j"
"/m/02m0kh"
"/m/01l0ty"
"/m/03cmqbt"
"/m/0g5rkt4"
"/m/02dd5z"
"/m/01gr8h"
"/m/01vr3v"
"/m/09g34_"
"/m/09cd0m"
"/m/03h11s3"
"/m/05ms3p0"
"/m/04lfc70"
"/m/06dy2k"
"/m/013z8m"
"/m/0ftwg"
"/m/0fk55"
"/m/06bkf"
"/m/0c_lbq"
"/m/0301xt"
"/m/01kb9y"
"/m/042199j"
"/m/03m3p6w"
"/m/0br_9j"
"/m/032m0b"
"/m/05y2yj"
"/m/01f9bg"
"/m/04hqxn"
"/m/068y7m"
"/m/06w4lv"
"/m/0ffk5n"
"/m/03gy1h2"
"/m/04wysy"
"/m/04fh1b"
"/m/01h4n"
"/m/044bp_"
"/m/0dtkkb"
"/m/0fp4n"
"/m/0166vx"
"/m/047q05d"
"/m/0c50f"
"/m/01srl7"
"/m/0fpxlz9"
"/m/03lnnd"
"/m/02pj9yr"
"/m/04118b"
"/m/0bdynxs"
"/m/01gby2"
"/m/0dn1_0"
"/m/062szv5"
"/m/062zk4r"
"/m/043_z22"
"/m/097r55"
"/m/035b50"
"/m/01hphz"
"/m/033fjj"
"/m/0b3zsn"
"/m/04lhnps"
"/m/08c25t"
"/m/05sng"
"/m/05bzpzx"
"/m/064rb5l"
"/m/01km_m"
"/m/059v8"
"/m/03b_13l"
"/m/09c8kp"
"/m/05ztd1"
"/m/04c28"
"/m/03sk2"
"/m/04jtjvt"
"/m/03hjx6f"
"/m/027936c"
"/m/03nvq"
"/m/03nz70"
"/m/01g3rx"
"/m/02wz7j"
"/m/04kdwcx"
"/m/04_8lfc"
"/m/033qt1"
"/m/08j1fb"
"/m/07wsyr"
"/m/06vb7b"
"/m/012fh"
"/m/0dm3xpw"
"/m/09r2kh"
"/m/02ry8mk"
"/m/029q52"
"/m/026d074"
"/m/013y54"
  }

  ?s wdt:P646 ?freebaseID .

  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" . }

}